### ISSUE TITLE
Optional ticking noise during work phase

### ISSUE THREAD

**Issue by jimmylad** [i207M/Pomodoro-Improved-Strict-Workflow#1]
Hi, thanks for forking. Please could you add this feature that I always wanted in Strict Workflow?

A checkbox on the options which adds a ticking sound (like this https://www.youtube.com/watch?v=euCViLHKFrk) during the work phase.

Thanks, James

**Comment by i207M** [comment]
ok. got that.

**Comment by i207M** [comment]
I've added the feature in v2.1.0 : )
Have fun!
If no bugs are found, this issue will be closed in 7 days.

**Comment by i207M** [comment]
however, custom background music is not supported yet.

**Comment by i207M** [comment]
If one wants to customize background music, please replace './resources/bgm.mp3'

**Comment by jimmylad** [comment]
Awesome thanks!

**Comment by jimmylad** [comment]
I just found that the context menu "Start Timer" doesn't change to "Skip" anymore

**Comment by i207M** [comment]
emm... In fact I don't get it. Can you further explain that? 
By the way, I did change the function of context menu. Now it could not skip timer when working, in order to be 'strict'.

**Comment by jimmylad** [comment]
OK not related then. Pity I found the context menu to stop a session a nice feature.

**Comment by i207M** [comment]
I have an idea. It could have an option to enable skipping the timer of working by clicking the context menu 3 times.
I think it should not be easy to skip working timer, in order to be 'strict'.

what's your opinion about that?

**Comment by jimmylad** [comment]
Yes could do. I'm not too bothered about it being strict, if I need to stop a timer (due to a distraction perhaps) then I will. It just won't count towards your daily score.

**Comment by i207M** [comment]
sure
